package frc.lib;

import edu.wpi.first.math.system.plant.DCMotor;
import java.util.Objects;

public record JointConstants(
    double massKg,
    double lengthMeters,
    double radiusMeters,
    double moiKgMetersSquared,
    double gearing,
    DCMotor motor,
    int motorCount) {

  /**
   * Creates joint constants for the joint of an arm.
   *
   * @param massKg the joint's mass in kilograms.
   * @param lengthMeters the joint's length in meters.
   * @param radius the distance between the joint's pivot and the joint's center of mass in meters.
   * @param moiKgMetersSquared the joint's moment of inertia in kilograms meters squared.
   * @param gearing the gearing between the joint's motor and the joint's pivot.
   * @param motor the type of the joint's driving motor.
   * @param motorCount the number of the driving motors.
   */
  public JointConstants {
    Objects.requireNonNull(massKg);
    Objects.requireNonNull(lengthMeters);
    Objects.requireNonNull(radiusMeters);
    Objects.requireNonNull(moiKgMetersSquared);
    Objects.requireNonNull(gearing);
    Objects.requireNonNull(motor);
    Objects.requireNonNull(motorCount);
  }

  /**
   * Creates joint constants for the joint of an arm.
   *
   * @param massKg the joint's mass in kilograms.
   * @param length the joint's length in meters.
   * @param radius the distance between the joint's pivot and the joint's center of mass in meters.
   * @param moi the joint's moment of inertia in kilograms meters squared.
   * @param gearing the gearing between the joint's motor and the joint's pivot.
   * @param motor the type of the joint's driving motor.
   */
  public JointConstants(
      double massKg, double length, double radius, double moi, double gearing, DCMotor motor) {
    this(massKg, length, radius, moi, gearing, motor, 1);
  }

  /**
   * Calculates the torque generated by the joint's gearbox element for the feedforward matrix.
   *
   * @return the torque generated by the joint's gearbox element for the feedforward matrix.
   */
  public double torqueNm() {
    return gearing * motorCount * motor.KtNMPerAmp / motor.rOhms;
  }

  /**
   * Calculates the torque loss due to back-emf for the feedforward matrix.
   *
   * @return the torque loss due to back-emf for the feedforward matrix.
   */
  public double torqueLossNm() {
    return gearing
        * gearing
        * motorCount
        * motor.KtNMPerAmp
        / motor.rOhms
        / motor.KvRadPerSecPerVolt;
  }
}
